//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "ComExampleHelloWorld.h"
#include "ComExampleHelloWorldTest.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "org/junit/Assert.h"
#include "org/junit/Test.h"

__attribute__((unused)) static IOSObjectArray *ComExampleHelloWorldTest__Annotations$0();

@implementation ComExampleHelloWorldTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComExampleHelloWorldTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)testToString {
  OrgJunitAssert_assertEqualsWithId_withId_(@"Hello World - Java", [create_ComExampleHelloWorld_initWithNSString_(@"World") description]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 0, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(testToString);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&ComExampleHelloWorldTest__Annotations$0 };
  static const J2ObjcClassInfo _ComExampleHelloWorldTest = { "HelloWorldTest", "com.example", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComExampleHelloWorldTest;
}

@end

void ComExampleHelloWorldTest_init(ComExampleHelloWorldTest *self) {
  NSObject_init(self);
}

ComExampleHelloWorldTest *new_ComExampleHelloWorldTest_init() {
  J2OBJC_NEW_IMPL(ComExampleHelloWorldTest, init)
}

ComExampleHelloWorldTest *create_ComExampleHelloWorldTest_init() {
  J2OBJC_CREATE_IMPL(ComExampleHelloWorldTest, init)
}

IOSObjectArray *ComExampleHelloWorldTest__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComExampleHelloWorldTest)
