//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest")
#ifdef RESTRICT_ComGoogleGsonFunctionalStreamingTypeAdaptersTest
#define INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest 1
#endif
#undef RESTRICT_ComGoogleGsonFunctionalStreamingTypeAdaptersTest

#if !defined (ComGoogleGsonFunctionalStreamingTypeAdaptersTest_) && (INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest || defined(INCLUDE_ComGoogleGsonFunctionalStreamingTypeAdaptersTest))
#define ComGoogleGsonFunctionalStreamingTypeAdaptersTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFunctionalStreamingTypeAdaptersTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testDeserialize;

- (void)testDeserialize1dArray;

- (void)testDeserialize2dArray;

- (void)testDeserializeMap;

- (void)testDeserializeNullField;

- (void)testDeserializeNullObject;

- (void)testDeserializeWithCustomTypeAdapter;

- (void)testFromJsonTree;

- (void)testNullSafe;

- (void)testSerialize;

- (void)testSerialize1dArray;

- (void)testSerialize2dArray;

- (void)testSerializeMap;

- (void)testSerializeNullField;

- (void)testSerializeNullObject;

- (void)testSerializeWithCustomTypeAdapter;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalStreamingTypeAdaptersTest)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalStreamingTypeAdaptersTest_init(ComGoogleGsonFunctionalStreamingTypeAdaptersTest *self);

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest *new_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest *create_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest)

#endif

#if !defined (ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck_) && (INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest || defined(INCLUDE_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck))
#define ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck_

@protocol JavaUtilList;

@interface ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck : NSObject {
 @public
  jdouble horsePower_;
  id<JavaUtilList> passengers_;
}

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck, passengers_, id<JavaUtilList>)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck_init(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck *self);

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck *new_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck *create_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Truck)

#endif

#if !defined (ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person_) && (INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest || defined(INCLUDE_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person))
#define ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person_

@interface ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person : NSObject {
 @public
  jint age_;
  NSString *name_;
}

#pragma mark Public

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)name
                         withInt:(jint)age;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person, name_, NSString *)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person_initWithNSString_withInt_(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person *self, NSString *name, jint age);

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person *new_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person_initWithNSString_withInt_(NSString *name, jint age) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person *create_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person_initWithNSString_withInt_(NSString *name, jint age);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Person)

#endif

#if !defined (ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node_) && (INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest || defined(INCLUDE_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node))
#define ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node_

@interface ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node : NSObject {
 @public
  NSString *label_;
  ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *left_;
  ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *right_;
}

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)label;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node, label_, NSString *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node, left_, ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node, right_, ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node_initWithNSString_(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *self, NSString *label);

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *new_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node_initWithNSString_(NSString *label) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node *create_ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node_initWithNSString_(NSString *label);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalStreamingTypeAdaptersTest_Node)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonFunctionalStreamingTypeAdaptersTest")
