//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonJavaSerializationTest")
#ifdef RESTRICT_ComGoogleGsonJavaSerializationTest
#define INCLUDE_ALL_ComGoogleGsonJavaSerializationTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonJavaSerializationTest 1
#endif
#undef RESTRICT_ComGoogleGsonJavaSerializationTest

#if !defined (ComGoogleGsonJavaSerializationTest_) && (INCLUDE_ALL_ComGoogleGsonJavaSerializationTest || defined(INCLUDE_ComGoogleGsonJavaSerializationTest))
#define ComGoogleGsonJavaSerializationTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonJavaSerializationTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testListIsSerializable;

- (void)testMapIsSerializable;

- (void)testNumberIsSerializable;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJavaSerializationTest)

FOUNDATION_EXPORT void ComGoogleGsonJavaSerializationTest_init(ComGoogleGsonJavaSerializationTest *self);

FOUNDATION_EXPORT ComGoogleGsonJavaSerializationTest *new_ComGoogleGsonJavaSerializationTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonJavaSerializationTest *create_ComGoogleGsonJavaSerializationTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJavaSerializationTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonJavaSerializationTest")
