//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "ComGoogleGsonAnnotationsSerializedName.h"
#include "ComGoogleGsonCommonMoreAsserts.h"
#include "ComGoogleGsonDopplJsonCompare.h"
#include "ComGoogleGsonFunctionalEnumTest.h"
#include "ComGoogleGsonGson.h"
#include "ComGoogleGsonGsonBuilder.h"
#include "ComGoogleGsonJsonDeserializationContext.h"
#include "ComGoogleGsonJsonDeserializer.h"
#include "ComGoogleGsonJsonElement.h"
#include "ComGoogleGsonJsonPrimitive.h"
#include "ComGoogleGsonJsonSerializationContext.h"
#include "ComGoogleGsonJsonSerializer.h"
#include "ComGoogleGsonReflectTypeToken.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/reflect/Type.h"
#include "java/util/ArrayList.h"
#include "java/util/Collection.h"
#include "java/util/EnumSet.h"
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFunctionalEnumTest () {
 @public
  ComGoogleGsonGson *gson_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalEnumTest, gson_, ComGoogleGsonGson *)

@interface ComGoogleGsonFunctionalEnumTest_1 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_1)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_1_init(ComGoogleGsonFunctionalEnumTest_1 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_1 *new_ComGoogleGsonFunctionalEnumTest_1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_1 *create_ComGoogleGsonFunctionalEnumTest_1_init();

@interface ComGoogleGsonFunctionalEnumTest_2 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_2)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_2_init(ComGoogleGsonFunctionalEnumTest_2 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_2 *new_ComGoogleGsonFunctionalEnumTest_2_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_2 *create_ComGoogleGsonFunctionalEnumTest_2_init();

typedef NS_ENUM(NSUInteger, ComGoogleGsonFunctionalEnumTest_MyEnum_Enum) {
  ComGoogleGsonFunctionalEnumTest_MyEnum_Enum_VALUE1 = 0,
  ComGoogleGsonFunctionalEnumTest_MyEnum_Enum_VALUE2 = 1,
};

@interface ComGoogleGsonFunctionalEnumTest_MyEnum : JavaLangEnum < NSCopying >

+ (IOSObjectArray *)values;

+ (ComGoogleGsonFunctionalEnumTest_MyEnum *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_MyEnum)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_values_[];

inline ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_get_VALUE1();
J2OBJC_ENUM_CONSTANT(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1)

inline ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_get_VALUE2();
J2OBJC_ENUM_CONSTANT(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE2)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_MyEnum_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_MyEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *ComGoogleGsonFunctionalEnumTest_MyEnum_values();

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalEnumTest_MyEnum)

@interface ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields : NSObject {
 @public
  ComGoogleGsonFunctionalEnumTest_MyEnum *value1_;
  ComGoogleGsonFunctionalEnumTest_MyEnum *value2_;
}

- (instancetype)init;

- (NSString *)getExpectedJson;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields, value1_, ComGoogleGsonFunctionalEnumTest_MyEnum *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields, value2_, ComGoogleGsonFunctionalEnumTest_MyEnum *)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *new_ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *create_ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields)

@interface ComGoogleGsonFunctionalEnumTest_3 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_3)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_3_init(ComGoogleGsonFunctionalEnumTest_3 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_3 *new_ComGoogleGsonFunctionalEnumTest_3_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_3 *create_ComGoogleGsonFunctionalEnumTest_3_init();

@interface ComGoogleGsonFunctionalEnumTest_4 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_4)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_4_init(ComGoogleGsonFunctionalEnumTest_4 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_4 *new_ComGoogleGsonFunctionalEnumTest_4_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_4 *create_ComGoogleGsonFunctionalEnumTest_4_init();

@interface ComGoogleGsonFunctionalEnumTest_5 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_5)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_5_init(ComGoogleGsonFunctionalEnumTest_5 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_5 *new_ComGoogleGsonFunctionalEnumTest_5_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_5 *create_ComGoogleGsonFunctionalEnumTest_5_init();

@interface ComGoogleGsonFunctionalEnumTest_6 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_6)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_6_init(ComGoogleGsonFunctionalEnumTest_6 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_6 *new_ComGoogleGsonFunctionalEnumTest_6_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_6 *create_ComGoogleGsonFunctionalEnumTest_6_init();

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_Roshambo_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo *self, NSString *__name, jint __ordinal);

@interface ComGoogleGsonFunctionalEnumTest_Roshambo_1 : ComGoogleGsonFunctionalEnumTest_Roshambo < NSCopying >

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_Roshambo_1)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_Roshambo_1_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo_1 *self, NSString *__name, jint __ordinal);

@interface ComGoogleGsonFunctionalEnumTest_Roshambo_2 : ComGoogleGsonFunctionalEnumTest_Roshambo < NSCopying >

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_Roshambo_2)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_Roshambo_2_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo_2 *self, NSString *__name, jint __ordinal);

@interface ComGoogleGsonFunctionalEnumTest_Roshambo_3 : ComGoogleGsonFunctionalEnumTest_Roshambo < NSCopying >

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_Roshambo_3)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_Roshambo_3_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo_3 *self, NSString *__name, jint __ordinal);

@interface ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonJsonElement *)serializeWithId:(ComGoogleGsonFunctionalEnumTest_Roshambo *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                              withJavaLangReflectType:(id<JavaLangReflectType>)classOfT
                                          withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter *self);

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter *new_ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter *create_ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter)

__attribute__((unused)) static void ComGoogleGsonFunctionalEnumTest_Gender_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Gender *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *ComGoogleGsonFunctionalEnumTest_Gender__Annotations$0();

__attribute__((unused)) static IOSObjectArray *ComGoogleGsonFunctionalEnumTest_Gender__Annotations$1();

@implementation ComGoogleGsonFunctionalEnumTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)setUp {
  [super setUp];
  JreStrongAssignAndConsume(&gson_, new_ComGoogleGsonGson_init());
}

- (void)testTopLevelEnumSerialization {
  NSString *result = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1)];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(JreStrcat("C$C", '"', [((ComGoogleGsonFunctionalEnumTest_MyEnum *) nil_chk(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1))) description], '"'), result);
}

- (void)testTopLevelEnumDeserialization {
  ComGoogleGsonFunctionalEnumTest_MyEnum *result = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:JreStrcat("C$C", '"', [((ComGoogleGsonFunctionalEnumTest_MyEnum *) nil_chk(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1))) description], '"') withIOSClass:ComGoogleGsonFunctionalEnumTest_MyEnum_class_()];
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1), result);
}

- (void)testCollectionOfEnumsSerialization {
  id<JavaLangReflectType> type = [create_ComGoogleGsonFunctionalEnumTest_1_init() getType];
  id<JavaUtilCollection> target = create_JavaUtilArrayList_init();
  [target addWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1)];
  [target addWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE2)];
  NSString *expectedJson = @"[\"VALUE1\",\"VALUE2\"]";
  NSString *actualJson = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:target];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(expectedJson, actualJson);
  actualJson = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:target withJavaLangReflectType:type];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(expectedJson, actualJson);
}

- (void)testCollectionOfEnumsDeserialization {
  id<JavaLangReflectType> type = [create_ComGoogleGsonFunctionalEnumTest_2_init() getType];
  NSString *json = @"[\"VALUE1\",\"VALUE2\"]";
  id<JavaUtilCollection> target = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withJavaLangReflectType:type];
  ComGoogleGsonCommonMoreAsserts_assertContainsWithJavaUtilCollection_withId_(target, JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1));
  ComGoogleGsonCommonMoreAsserts_assertContainsWithJavaUtilCollection_withId_(target, JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE2));
}

- (void)testClassWithEnumFieldSerialization {
  ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *target = create_ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init();
  ComGoogleGsonDopplJsonCompare_jsonSameAssertWithNSString_withNSString_([target getExpectedJson], [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:target]);
}

- (void)testClassWithEnumFieldDeserialization {
  NSString *json = @"{value1:'VALUE1',value2:'VALUE2'}";
  ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *target = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_class_()];
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1), ((ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *) nil_chk(target))->value1_);
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE2), target->value2_);
}

- (void)testEnumSubclass {
  JunitFrameworkTestCase_assertFalseWithBoolean_(ComGoogleGsonFunctionalEnumTest_Roshambo_class_() == [((ComGoogleGsonFunctionalEnumTest_Roshambo *) nil_chk(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK))) java_getClass]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"\"ROCK\"", [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK)]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"[\"ROCK\",\"PAPER\",\"SCISSORS\"]", [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:JavaUtilEnumSet_allOfWithIOSClass_(ComGoogleGsonFunctionalEnumTest_Roshambo_class_())]);
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK), [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:@"\"ROCK\"" withIOSClass:ComGoogleGsonFunctionalEnumTest_Roshambo_class_()]);
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JavaUtilEnumSet_allOfWithIOSClass_(ComGoogleGsonFunctionalEnumTest_Roshambo_class_()), [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:@"[\"ROCK\",\"PAPER\",\"SCISSORS\"]" withJavaLangReflectType:[create_ComGoogleGsonFunctionalEnumTest_3_init() getType]]);
}

- (void)testEnumSubclassWithRegisteredTypeAdapter {
  JreStrongAssign(&gson_, [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeHierarchyAdapterWithIOSClass:ComGoogleGsonFunctionalEnumTest_Roshambo_class_() withId:create_ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init()])) create]);
  JunitFrameworkTestCase_assertFalseWithBoolean_(ComGoogleGsonFunctionalEnumTest_Roshambo_class_() == [((ComGoogleGsonFunctionalEnumTest_Roshambo *) nil_chk(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK))) java_getClass]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"\"123ROCK\"", [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK)]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"[\"123ROCK\",\"123PAPER\",\"123SCISSORS\"]", [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:JavaUtilEnumSet_allOfWithIOSClass_(ComGoogleGsonFunctionalEnumTest_Roshambo_class_())]);
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK), [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:@"\"123ROCK\"" withIOSClass:ComGoogleGsonFunctionalEnumTest_Roshambo_class_()]);
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JavaUtilEnumSet_allOfWithIOSClass_(ComGoogleGsonFunctionalEnumTest_Roshambo_class_()), [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:@"[\"123ROCK\",\"123PAPER\",\"123SCISSORS\"]" withJavaLangReflectType:[create_ComGoogleGsonFunctionalEnumTest_4_init() getType]]);
}

- (void)testEnumSubclassAsParameterizedType {
  id<JavaUtilCollection> list = create_JavaUtilArrayList_init();
  [list addWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK)];
  [list addWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER)];
  NSString *json = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:list];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"[\"ROCK\",\"PAPER\"]", json);
  id<JavaLangReflectType> collectionType = [create_ComGoogleGsonFunctionalEnumTest_5_init() getType];
  id<JavaUtilCollection> actualJsonList = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withJavaLangReflectType:collectionType];
  ComGoogleGsonCommonMoreAsserts_assertContainsWithJavaUtilCollection_withId_(actualJsonList, JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK));
  ComGoogleGsonCommonMoreAsserts_assertContainsWithJavaUtilCollection_withId_(actualJsonList, JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER));
}

- (void)testEnumCaseMapping {
  JunitFrameworkTestCase_assertEqualsWithId_withId_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Gender, MALE), [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:@"\"boy\"" withIOSClass:ComGoogleGsonFunctionalEnumTest_Gender_class_()]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"\"boy\"", [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Gender, MALE) withJavaLangReflectType:ComGoogleGsonFunctionalEnumTest_Gender_class_()]);
}

- (void)testEnumSet {
  JavaUtilEnumSet *foo = JavaUtilEnumSet_ofWithJavaLangEnum_withJavaLangEnum_(JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK), JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER));
  NSString *json = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:foo];
  id<JavaLangReflectType> type = [create_ComGoogleGsonFunctionalEnumTest_6_init() getType];
  JavaUtilEnumSet *bar = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withJavaLangReflectType:type];
  JunitFrameworkTestCase_assertTrueWithBoolean_([((JavaUtilEnumSet *) nil_chk(bar)) containsWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK)]);
  JunitFrameworkTestCase_assertTrueWithBoolean_([bar containsWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER)]);
  JunitFrameworkTestCase_assertFalseWithBoolean_([bar containsWithId:JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, SCISSORS)]);
}

- (void)dealloc {
  RELEASE_(gson_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(setUp);
  methods[2].selector = @selector(testTopLevelEnumSerialization);
  methods[3].selector = @selector(testTopLevelEnumDeserialization);
  methods[4].selector = @selector(testCollectionOfEnumsSerialization);
  methods[5].selector = @selector(testCollectionOfEnumsDeserialization);
  methods[6].selector = @selector(testClassWithEnumFieldSerialization);
  methods[7].selector = @selector(testClassWithEnumFieldDeserialization);
  methods[8].selector = @selector(testEnumSubclass);
  methods[9].selector = @selector(testEnumSubclassWithRegisteredTypeAdapter);
  methods[10].selector = @selector(testEnumSubclassAsParameterizedType);
  methods[11].selector = @selector(testEnumCaseMapping);
  methods[12].selector = @selector(testEnumSet);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "gson_", "LComGoogleGsonGson;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaLangException;", "LComGoogleGsonFunctionalEnumTest_MyEnum;LComGoogleGsonFunctionalEnumTest_ClassWithEnumFields;LComGoogleGsonFunctionalEnumTest_Roshambo;LComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter;LComGoogleGsonFunctionalEnumTest_Gender;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest = { "EnumTest", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x1, 13, 1, -1, 1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalEnumTest;
}

@end

void ComGoogleGsonFunctionalEnumTest_init(ComGoogleGsonFunctionalEnumTest *self) {
  JunitFrameworkTestCase_init(self);
}

ComGoogleGsonFunctionalEnumTest *new_ComGoogleGsonFunctionalEnumTest_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest, init)
}

ComGoogleGsonFunctionalEnumTest *create_ComGoogleGsonFunctionalEnumTest_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalEnumTest)

@implementation ComGoogleGsonFunctionalEnumTest_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;", "testCollectionOfEnumsSerialization", "Lcom/google/gson/reflect/TypeToken<Ljava/util/Collection<Lcom/google/gson/functional/EnumTest$MyEnum;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_1 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_1;
}

@end

void ComGoogleGsonFunctionalEnumTest_1_init(ComGoogleGsonFunctionalEnumTest_1 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalEnumTest_1 *new_ComGoogleGsonFunctionalEnumTest_1_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_1, init)
}

ComGoogleGsonFunctionalEnumTest_1 *create_ComGoogleGsonFunctionalEnumTest_1_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_1, init)
}

@implementation ComGoogleGsonFunctionalEnumTest_2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;", "testCollectionOfEnumsDeserialization", "Lcom/google/gson/reflect/TypeToken<Ljava/util/Collection<Lcom/google/gson/functional/EnumTest$MyEnum;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_2 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_2;
}

@end

void ComGoogleGsonFunctionalEnumTest_2_init(ComGoogleGsonFunctionalEnumTest_2 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalEnumTest_2 *new_ComGoogleGsonFunctionalEnumTest_2_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_2, init)
}

ComGoogleGsonFunctionalEnumTest_2 *create_ComGoogleGsonFunctionalEnumTest_2_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_2, init)
}

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonFunctionalEnumTest_MyEnum)

ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_values_[2];

@implementation ComGoogleGsonFunctionalEnumTest_MyEnum

+ (IOSObjectArray *)values {
  return ComGoogleGsonFunctionalEnumTest_MyEnum_values();
}

+ (ComGoogleGsonFunctionalEnumTest_MyEnum *)valueOfWithNSString:(NSString *)name {
  return ComGoogleGsonFunctionalEnumTest_MyEnum_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LComGoogleGsonFunctionalEnumTest_MyEnum;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalEnumTest_MyEnum;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "VALUE1", "LComGoogleGsonFunctionalEnumTest_MyEnum;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "VALUE2", "LComGoogleGsonFunctionalEnumTest_MyEnum;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1), &JreEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE2), "LComGoogleGsonFunctionalEnumTest;", "Ljava/lang/Enum<Lcom/google/gson/functional/EnumTest$MyEnum;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_MyEnum = { "MyEnum", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x401a, 2, 2, 4, -1, -1, 5, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_MyEnum;
}

+ (void)initialize {
  if (self == [ComGoogleGsonFunctionalEnumTest_MyEnum class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 2 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"VALUE1", @"VALUE2",
    };
    for (jint i = 0; i < 2; i++) {
      (ComGoogleGsonFunctionalEnumTest_MyEnum_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      ComGoogleGsonFunctionalEnumTest_MyEnum_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(ComGoogleGsonFunctionalEnumTest_MyEnum)
  }
}

@end

void ComGoogleGsonFunctionalEnumTest_MyEnum_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_MyEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *ComGoogleGsonFunctionalEnumTest_MyEnum_values() {
  ComGoogleGsonFunctionalEnumTest_MyEnum_initialize();
  return [IOSObjectArray arrayWithObjects:ComGoogleGsonFunctionalEnumTest_MyEnum_values_ count:2 type:ComGoogleGsonFunctionalEnumTest_MyEnum_class_()];
}

ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_valueOfWithNSString_(NSString *name) {
  ComGoogleGsonFunctionalEnumTest_MyEnum_initialize();
  for (int i = 0; i < 2; i++) {
    ComGoogleGsonFunctionalEnumTest_MyEnum *e = ComGoogleGsonFunctionalEnumTest_MyEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComGoogleGsonFunctionalEnumTest_MyEnum *ComGoogleGsonFunctionalEnumTest_MyEnum_fromOrdinal(NSUInteger ordinal) {
  ComGoogleGsonFunctionalEnumTest_MyEnum_initialize();
  if (ordinal >= 2) {
    return nil;
  }
  return ComGoogleGsonFunctionalEnumTest_MyEnum_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalEnumTest_MyEnum)

@implementation ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)getExpectedJson {
  return JreStrcat("$@$@$", @"{\"value1\":\"", value1_, @"\",\"value2\":\"", value2_, @"\"}");
}

- (void)dealloc {
  RELEASE_(value1_);
  RELEASE_(value2_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getExpectedJson);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value1_", "LComGoogleGsonFunctionalEnumTest_MyEnum;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "value2_", "LComGoogleGsonFunctionalEnumTest_MyEnum;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields = { "ClassWithEnumFields", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 2, 2, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields;
}

@end

void ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *self) {
  NSObject_init(self);
  JreStrongAssign(&self->value1_, JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE1));
  JreStrongAssign(&self->value2_, JreLoadEnum(ComGoogleGsonFunctionalEnumTest_MyEnum, VALUE2));
}

ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *new_ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields, init)
}

ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields *create_ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalEnumTest_ClassWithEnumFields)

@implementation ComGoogleGsonFunctionalEnumTest_3

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_3_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;", "testEnumSubclass", "Lcom/google/gson/reflect/TypeToken<Ljava/util/Set<Lcom/google/gson/functional/EnumTest$Roshambo;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_3 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_3;
}

@end

void ComGoogleGsonFunctionalEnumTest_3_init(ComGoogleGsonFunctionalEnumTest_3 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalEnumTest_3 *new_ComGoogleGsonFunctionalEnumTest_3_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_3, init)
}

ComGoogleGsonFunctionalEnumTest_3 *create_ComGoogleGsonFunctionalEnumTest_3_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_3, init)
}

@implementation ComGoogleGsonFunctionalEnumTest_4

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_4_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;", "testEnumSubclassWithRegisteredTypeAdapter", "Lcom/google/gson/reflect/TypeToken<Ljava/util/Set<Lcom/google/gson/functional/EnumTest$Roshambo;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_4 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_4;
}

@end

void ComGoogleGsonFunctionalEnumTest_4_init(ComGoogleGsonFunctionalEnumTest_4 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalEnumTest_4 *new_ComGoogleGsonFunctionalEnumTest_4_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_4, init)
}

ComGoogleGsonFunctionalEnumTest_4 *create_ComGoogleGsonFunctionalEnumTest_4_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_4, init)
}

@implementation ComGoogleGsonFunctionalEnumTest_5

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_5_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;", "testEnumSubclassAsParameterizedType", "Lcom/google/gson/reflect/TypeToken<Ljava/util/Collection<Lcom/google/gson/functional/EnumTest$Roshambo;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_5 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_5;
}

@end

void ComGoogleGsonFunctionalEnumTest_5_init(ComGoogleGsonFunctionalEnumTest_5 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalEnumTest_5 *new_ComGoogleGsonFunctionalEnumTest_5_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_5, init)
}

ComGoogleGsonFunctionalEnumTest_5 *create_ComGoogleGsonFunctionalEnumTest_5_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_5, init)
}

@implementation ComGoogleGsonFunctionalEnumTest_6

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_6_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest;", "testEnumSet", "Lcom/google/gson/reflect/TypeToken<Ljava/util/EnumSet<Lcom/google/gson/functional/EnumTest$Roshambo;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_6 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_6;
}

@end

void ComGoogleGsonFunctionalEnumTest_6_init(ComGoogleGsonFunctionalEnumTest_6 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalEnumTest_6 *new_ComGoogleGsonFunctionalEnumTest_6_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_6, init)
}

ComGoogleGsonFunctionalEnumTest_6 *create_ComGoogleGsonFunctionalEnumTest_6_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_6, init)
}

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonFunctionalEnumTest_Roshambo)

ComGoogleGsonFunctionalEnumTest_Roshambo *ComGoogleGsonFunctionalEnumTest_Roshambo_values_[3];

@implementation ComGoogleGsonFunctionalEnumTest_Roshambo

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

+ (IOSObjectArray *)values {
  return ComGoogleGsonFunctionalEnumTest_Roshambo_values();
}

+ (ComGoogleGsonFunctionalEnumTest_Roshambo *)valueOfWithNSString:(NSString *)name {
  return ComGoogleGsonFunctionalEnumTest_Roshambo_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x400, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(defeats);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ROCK", "LComGoogleGsonFunctionalEnumTest_Roshambo;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "PAPER", "LComGoogleGsonFunctionalEnumTest_Roshambo;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "SCISSORS", "LComGoogleGsonFunctionalEnumTest_Roshambo;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK), &JreEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER), &JreEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, SCISSORS), "LComGoogleGsonFunctionalEnumTest;", "Ljava/lang/Enum<Lcom/google/gson/functional/EnumTest$Roshambo;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_Roshambo = { "Roshambo", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x4409, 3, 3, 5, -1, -1, 6, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_Roshambo;
}

+ (void)initialize {
  if (self == [ComGoogleGsonFunctionalEnumTest_Roshambo class]) {
    size_t allocSize = 0;
    size_t objSize_ROCK = class_getInstanceSize([ComGoogleGsonFunctionalEnumTest_Roshambo_1 class]);
    allocSize += objSize_ROCK;
    size_t objSize_PAPER = class_getInstanceSize([ComGoogleGsonFunctionalEnumTest_Roshambo_2 class]);
    allocSize += objSize_PAPER;
    size_t objSize_SCISSORS = class_getInstanceSize([ComGoogleGsonFunctionalEnumTest_Roshambo_3 class]);
    allocSize += objSize_SCISSORS;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK) = e = objc_constructInstance([ComGoogleGsonFunctionalEnumTest_Roshambo_1 class], (void *)ptr), ptr += objSize_ROCK);
    ComGoogleGsonFunctionalEnumTest_Roshambo_1_initWithNSString_withInt_(e, @"ROCK", 0);
    (JreEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER) = e = objc_constructInstance([ComGoogleGsonFunctionalEnumTest_Roshambo_2 class], (void *)ptr), ptr += objSize_PAPER);
    ComGoogleGsonFunctionalEnumTest_Roshambo_2_initWithNSString_withInt_(e, @"PAPER", 1);
    (JreEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, SCISSORS) = e = objc_constructInstance([ComGoogleGsonFunctionalEnumTest_Roshambo_3 class], (void *)ptr), ptr += objSize_SCISSORS);
    ComGoogleGsonFunctionalEnumTest_Roshambo_3_initWithNSString_withInt_(e, @"SCISSORS", 2);
    J2OBJC_SET_INITIALIZED(ComGoogleGsonFunctionalEnumTest_Roshambo)
  }
}

@end

void ComGoogleGsonFunctionalEnumTest_Roshambo_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *ComGoogleGsonFunctionalEnumTest_Roshambo_values() {
  ComGoogleGsonFunctionalEnumTest_Roshambo_initialize();
  return [IOSObjectArray arrayWithObjects:ComGoogleGsonFunctionalEnumTest_Roshambo_values_ count:3 type:ComGoogleGsonFunctionalEnumTest_Roshambo_class_()];
}

ComGoogleGsonFunctionalEnumTest_Roshambo *ComGoogleGsonFunctionalEnumTest_Roshambo_valueOfWithNSString_(NSString *name) {
  ComGoogleGsonFunctionalEnumTest_Roshambo_initialize();
  for (int i = 0; i < 3; i++) {
    ComGoogleGsonFunctionalEnumTest_Roshambo *e = ComGoogleGsonFunctionalEnumTest_Roshambo_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComGoogleGsonFunctionalEnumTest_Roshambo *ComGoogleGsonFunctionalEnumTest_Roshambo_fromOrdinal(NSUInteger ordinal) {
  ComGoogleGsonFunctionalEnumTest_Roshambo_initialize();
  if (ordinal >= 3) {
    return nil;
  }
  return ComGoogleGsonFunctionalEnumTest_Roshambo_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalEnumTest_Roshambo)

@implementation ComGoogleGsonFunctionalEnumTest_Roshambo_1

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats {
  return JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, SCISSORS);
}

- (void)dealloc {
  JreCheckFinalize(self, [ComGoogleGsonFunctionalEnumTest_Roshambo_1 class]);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(defeats);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest_Roshambo;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_Roshambo_1 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0xc018, 1, 0, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_Roshambo_1;
}

@end

void ComGoogleGsonFunctionalEnumTest_Roshambo_1_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo_1 *self, NSString *__name, jint __ordinal) {
  ComGoogleGsonFunctionalEnumTest_Roshambo_initWithNSString_withInt_(self, __name, __ordinal);
}

@implementation ComGoogleGsonFunctionalEnumTest_Roshambo_2

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats {
  return JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, ROCK);
}

- (void)dealloc {
  JreCheckFinalize(self, [ComGoogleGsonFunctionalEnumTest_Roshambo_2 class]);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(defeats);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest_Roshambo;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_Roshambo_2 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0xc018, 1, 0, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_Roshambo_2;
}

@end

void ComGoogleGsonFunctionalEnumTest_Roshambo_2_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo_2 *self, NSString *__name, jint __ordinal) {
  ComGoogleGsonFunctionalEnumTest_Roshambo_initWithNSString_withInt_(self, __name, __ordinal);
}

@implementation ComGoogleGsonFunctionalEnumTest_Roshambo_3

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)defeats {
  return JreLoadEnum(ComGoogleGsonFunctionalEnumTest_Roshambo, PAPER);
}

- (void)dealloc {
  JreCheckFinalize(self, [ComGoogleGsonFunctionalEnumTest_Roshambo_3 class]);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(defeats);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalEnumTest_Roshambo;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_Roshambo_3 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0xc018, 1, 0, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_Roshambo_3;
}

@end

void ComGoogleGsonFunctionalEnumTest_Roshambo_3_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Roshambo_3 *self, NSString *__name, jint __ordinal) {
  ComGoogleGsonFunctionalEnumTest_Roshambo_initWithNSString_withInt_(self, __name, __ordinal);
}

@implementation ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonJsonElement *)serializeWithId:(ComGoogleGsonFunctionalEnumTest_Roshambo *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  return create_ComGoogleGsonJsonPrimitive_initWithNSString_(JreStrcat("$$", @"123", [((ComGoogleGsonFunctionalEnumTest_Roshambo *) nil_chk(src)) name]));
}

- (ComGoogleGsonFunctionalEnumTest_Roshambo *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                              withJavaLangReflectType:(id<JavaLangReflectType>)classOfT
                                          withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  return ComGoogleGsonFunctionalEnumTest_Roshambo_valueOfWithNSString_([((NSString *) nil_chk([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString])) java_substring:3]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalEnumTest_Roshambo;", 0x1, 2, 3, 4, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:);
  methods[2].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "serialize", "LComGoogleGsonFunctionalEnumTest_Roshambo;LJavaLangReflectType;LComGoogleGsonJsonSerializationContext;", "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalEnumTest;", "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Lcom/google/gson/functional/EnumTest$Roshambo;>;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/functional/EnumTest$Roshambo;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter = { "MyEnumTypeAdapter", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0xa, 3, 0, 5, -1, -1, 6, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter;
}

@end

void ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter *new_ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter, init)
}

ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter *create_ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalEnumTest_MyEnumTypeAdapter)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonFunctionalEnumTest_Gender)

ComGoogleGsonFunctionalEnumTest_Gender *ComGoogleGsonFunctionalEnumTest_Gender_values_[2];

@implementation ComGoogleGsonFunctionalEnumTest_Gender

+ (IOSObjectArray *)values {
  return ComGoogleGsonFunctionalEnumTest_Gender_values();
}

+ (ComGoogleGsonFunctionalEnumTest_Gender *)valueOfWithNSString:(NSString *)name {
  return ComGoogleGsonFunctionalEnumTest_Gender_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LComGoogleGsonFunctionalEnumTest_Gender;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalEnumTest_Gender;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "MALE", "LComGoogleGsonFunctionalEnumTest_Gender;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, 3 },
    { "FEMALE", "LComGoogleGsonFunctionalEnumTest_Gender;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, 5 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComGoogleGsonFunctionalEnumTest_Gender, MALE), (void *)&ComGoogleGsonFunctionalEnumTest_Gender__Annotations$0, &JreEnum(ComGoogleGsonFunctionalEnumTest_Gender, FEMALE), (void *)&ComGoogleGsonFunctionalEnumTest_Gender__Annotations$1, "LComGoogleGsonFunctionalEnumTest;", "Ljava/lang/Enum<Lcom/google/gson/functional/EnumTest$Gender;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalEnumTest_Gender = { "Gender", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x4019, 2, 2, 6, -1, -1, 7, -1 };
  return &_ComGoogleGsonFunctionalEnumTest_Gender;
}

+ (void)initialize {
  if (self == [ComGoogleGsonFunctionalEnumTest_Gender class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 2 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"MALE", @"FEMALE",
    };
    for (jint i = 0; i < 2; i++) {
      (ComGoogleGsonFunctionalEnumTest_Gender_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      ComGoogleGsonFunctionalEnumTest_Gender_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(ComGoogleGsonFunctionalEnumTest_Gender)
  }
}

@end

void ComGoogleGsonFunctionalEnumTest_Gender_initWithNSString_withInt_(ComGoogleGsonFunctionalEnumTest_Gender *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *ComGoogleGsonFunctionalEnumTest_Gender_values() {
  ComGoogleGsonFunctionalEnumTest_Gender_initialize();
  return [IOSObjectArray arrayWithObjects:ComGoogleGsonFunctionalEnumTest_Gender_values_ count:2 type:ComGoogleGsonFunctionalEnumTest_Gender_class_()];
}

ComGoogleGsonFunctionalEnumTest_Gender *ComGoogleGsonFunctionalEnumTest_Gender_valueOfWithNSString_(NSString *name) {
  ComGoogleGsonFunctionalEnumTest_Gender_initialize();
  for (int i = 0; i < 2; i++) {
    ComGoogleGsonFunctionalEnumTest_Gender *e = ComGoogleGsonFunctionalEnumTest_Gender_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComGoogleGsonFunctionalEnumTest_Gender *ComGoogleGsonFunctionalEnumTest_Gender_fromOrdinal(NSUInteger ordinal) {
  ComGoogleGsonFunctionalEnumTest_Gender_initialize();
  if (ordinal >= 2) {
    return nil;
  }
  return ComGoogleGsonFunctionalEnumTest_Gender_values_[ordinal];
}

IOSObjectArray *ComGoogleGsonFunctionalEnumTest_Gender__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComGoogleGsonAnnotationsSerializedName([IOSObjectArray arrayWithLength:0 type:NSString_class_()], @"boy") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *ComGoogleGsonFunctionalEnumTest_Gender__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComGoogleGsonAnnotationsSerializedName([IOSObjectArray arrayWithLength:0 type:NSString_class_()], @"girl") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalEnumTest_Gender)
