//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonFieldAttributesTest")
#ifdef RESTRICT_ComGoogleGsonFieldAttributesTest
#define INCLUDE_ALL_ComGoogleGsonFieldAttributesTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonFieldAttributesTest 1
#endif
#undef RESTRICT_ComGoogleGsonFieldAttributesTest

#if !defined (ComGoogleGsonFieldAttributesTest_) && (INCLUDE_ALL_ComGoogleGsonFieldAttributesTest || defined(INCLUDE_ComGoogleGsonFieldAttributesTest))
#define ComGoogleGsonFieldAttributesTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFieldAttributesTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testDeclaredTypeAndClass;

- (void)testDeclaringClass;

- (void)testIsSynthetic;

- (void)testModifiers;

- (void)testName;

- (void)testNullField;

#pragma mark Protected

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFieldAttributesTest)

FOUNDATION_EXPORT void ComGoogleGsonFieldAttributesTest_init(ComGoogleGsonFieldAttributesTest *self);

FOUNDATION_EXPORT ComGoogleGsonFieldAttributesTest *new_ComGoogleGsonFieldAttributesTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFieldAttributesTest *create_ComGoogleGsonFieldAttributesTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldAttributesTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonFieldAttributesTest")
