//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest")
#ifdef RESTRICT_ComGoogleGsonGsonTypeAdapterTest
#define INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest 1
#endif
#undef RESTRICT_ComGoogleGsonGsonTypeAdapterTest
#ifdef INCLUDE_ComGoogleGsonGsonTypeAdapterTest_Concrete
#define INCLUDE_ComGoogleGsonGsonTypeAdapterTest_Abstract 1
#endif

#if !defined (ComGoogleGsonGsonTypeAdapterTest_) && (INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest || defined(INCLUDE_ComGoogleGsonGsonTypeAdapterTest))
#define ComGoogleGsonGsonTypeAdapterTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonGsonTypeAdapterTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testDefaultTypeAdapterThrowsParseException;

- (void)testDeserializerForAbstractClass;

- (void)testTypeAdapterDoesNotAffectNonAdaptedTypes;

- (void)testTypeAdapterProperlyConvertsTypes;

- (void)testTypeAdapterThrowsException;

#pragma mark Protected

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGsonTypeAdapterTest)

FOUNDATION_EXPORT void ComGoogleGsonGsonTypeAdapterTest_init(ComGoogleGsonGsonTypeAdapterTest *self);

FOUNDATION_EXPORT ComGoogleGsonGsonTypeAdapterTest *new_ComGoogleGsonGsonTypeAdapterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonGsonTypeAdapterTest *create_ComGoogleGsonGsonTypeAdapterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGsonTypeAdapterTest)

#endif

#if !defined (ComGoogleGsonGsonTypeAdapterTest_Abstract_) && (INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest || defined(INCLUDE_ComGoogleGsonGsonTypeAdapterTest_Abstract))
#define ComGoogleGsonGsonTypeAdapterTest_Abstract_

@interface ComGoogleGsonGsonTypeAdapterTest_Abstract : NSObject {
 @public
  NSString *a_;
}

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGsonTypeAdapterTest_Abstract)

J2OBJC_FIELD_SETTER(ComGoogleGsonGsonTypeAdapterTest_Abstract, a_, NSString *)

FOUNDATION_EXPORT void ComGoogleGsonGsonTypeAdapterTest_Abstract_init(ComGoogleGsonGsonTypeAdapterTest_Abstract *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGsonTypeAdapterTest_Abstract)

#endif

#if !defined (ComGoogleGsonGsonTypeAdapterTest_Concrete_) && (INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest || defined(INCLUDE_ComGoogleGsonGsonTypeAdapterTest_Concrete))
#define ComGoogleGsonGsonTypeAdapterTest_Concrete_

@interface ComGoogleGsonGsonTypeAdapterTest_Concrete : ComGoogleGsonGsonTypeAdapterTest_Abstract {
 @public
  NSString *b_;
}

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGsonTypeAdapterTest_Concrete)

J2OBJC_FIELD_SETTER(ComGoogleGsonGsonTypeAdapterTest_Concrete, b_, NSString *)

FOUNDATION_EXPORT void ComGoogleGsonGsonTypeAdapterTest_Concrete_init(ComGoogleGsonGsonTypeAdapterTest_Concrete *self);

FOUNDATION_EXPORT ComGoogleGsonGsonTypeAdapterTest_Concrete *new_ComGoogleGsonGsonTypeAdapterTest_Concrete_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonGsonTypeAdapterTest_Concrete *create_ComGoogleGsonGsonTypeAdapterTest_Concrete_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGsonTypeAdapterTest_Concrete)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonGsonTypeAdapterTest")
