//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonFunctionalDelegateTypeAdapterTest")
#ifdef RESTRICT_ComGoogleGsonFunctionalDelegateTypeAdapterTest
#define INCLUDE_ALL_ComGoogleGsonFunctionalDelegateTypeAdapterTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonFunctionalDelegateTypeAdapterTest 1
#endif
#undef RESTRICT_ComGoogleGsonFunctionalDelegateTypeAdapterTest

#if !defined (ComGoogleGsonFunctionalDelegateTypeAdapterTest_) && (INCLUDE_ALL_ComGoogleGsonFunctionalDelegateTypeAdapterTest || defined(INCLUDE_ComGoogleGsonFunctionalDelegateTypeAdapterTest))
#define ComGoogleGsonFunctionalDelegateTypeAdapterTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFunctionalDelegateTypeAdapterTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testDelegateInvoked;

- (void)testDelegateInvokedOnStrings;

#pragma mark Protected

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalDelegateTypeAdapterTest)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalDelegateTypeAdapterTest_init(ComGoogleGsonFunctionalDelegateTypeAdapterTest *self);

FOUNDATION_EXPORT ComGoogleGsonFunctionalDelegateTypeAdapterTest *new_ComGoogleGsonFunctionalDelegateTypeAdapterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalDelegateTypeAdapterTest *create_ComGoogleGsonFunctionalDelegateTypeAdapterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalDelegateTypeAdapterTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonFunctionalDelegateTypeAdapterTest")
