//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RenameOrgJsonSimpleJSONValue")
#ifdef RESTRICT_RenameOrgJsonSimpleJSONValue
#define INCLUDE_ALL_RenameOrgJsonSimpleJSONValue 0
#else
#define INCLUDE_ALL_RenameOrgJsonSimpleJSONValue 1
#endif
#undef RESTRICT_RenameOrgJsonSimpleJSONValue

#if !defined (RenameOrgJsonSimpleJSONValue_) && (INCLUDE_ALL_RenameOrgJsonSimpleJSONValue || defined(INCLUDE_RenameOrgJsonSimpleJSONValue))
#define RenameOrgJsonSimpleJSONValue_

@class JavaIoReader;
@class JavaIoWriter;
@class JavaLangStringBuffer;

@interface RenameOrgJsonSimpleJSONValue : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)escapeWithNSString:(NSString *)s;

+ (id)parseWithJavaIoReader:(JavaIoReader *)inArg;

+ (id)parseWithNSString:(NSString *)s;

+ (id)parseWithExceptionWithJavaIoReader:(JavaIoReader *)inArg;

+ (id)parseWithExceptionWithNSString:(NSString *)s;

+ (NSString *)toJSONStringWithId:(id)value;

+ (void)writeJSONStringWithId:(id)value
             withJavaIoWriter:(JavaIoWriter *)outArg;

#pragma mark Package-Private

+ (void)escapeWithNSString:(NSString *)s
  withJavaLangStringBuffer:(JavaLangStringBuffer *)sb;

@end

J2OBJC_EMPTY_STATIC_INIT(RenameOrgJsonSimpleJSONValue)

FOUNDATION_EXPORT void RenameOrgJsonSimpleJSONValue_init(RenameOrgJsonSimpleJSONValue *self);

FOUNDATION_EXPORT RenameOrgJsonSimpleJSONValue *new_RenameOrgJsonSimpleJSONValue_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RenameOrgJsonSimpleJSONValue *create_RenameOrgJsonSimpleJSONValue_init();

FOUNDATION_EXPORT id RenameOrgJsonSimpleJSONValue_parseWithJavaIoReader_(JavaIoReader *inArg);

FOUNDATION_EXPORT id RenameOrgJsonSimpleJSONValue_parseWithNSString_(NSString *s);

FOUNDATION_EXPORT id RenameOrgJsonSimpleJSONValue_parseWithExceptionWithJavaIoReader_(JavaIoReader *inArg);

FOUNDATION_EXPORT id RenameOrgJsonSimpleJSONValue_parseWithExceptionWithNSString_(NSString *s);

FOUNDATION_EXPORT void RenameOrgJsonSimpleJSONValue_writeJSONStringWithId_withJavaIoWriter_(id value, JavaIoWriter *outArg);

FOUNDATION_EXPORT NSString *RenameOrgJsonSimpleJSONValue_toJSONStringWithId_(id value);

FOUNDATION_EXPORT NSString *RenameOrgJsonSimpleJSONValue_escapeWithNSString_(NSString *s);

FOUNDATION_EXPORT void RenameOrgJsonSimpleJSONValue_escapeWithNSString_withJavaLangStringBuffer_(NSString *s, JavaLangStringBuffer *sb);

J2OBJC_TYPE_LITERAL_HEADER(RenameOrgJsonSimpleJSONValue)

#endif

#pragma pop_macro("INCLUDE_ALL_RenameOrgJsonSimpleJSONValue")
