//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonFunctionalPrettyPrintingTest")
#ifdef RESTRICT_ComGoogleGsonFunctionalPrettyPrintingTest
#define INCLUDE_ALL_ComGoogleGsonFunctionalPrettyPrintingTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonFunctionalPrettyPrintingTest 1
#endif
#undef RESTRICT_ComGoogleGsonFunctionalPrettyPrintingTest

#if !defined (ComGoogleGsonFunctionalPrettyPrintingTest_) && (INCLUDE_ALL_ComGoogleGsonFunctionalPrettyPrintingTest || defined(INCLUDE_ComGoogleGsonFunctionalPrettyPrintingTest))
#define ComGoogleGsonFunctionalPrettyPrintingTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFunctionalPrettyPrintingTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testEmptyMapField;

- (void)testMap;

- (void)testMultipleArrays;

- (void)testPrettyPrintArrayOfObjects;

- (void)testPrettyPrintArrayOfPrimitiveArrays;

- (void)testPrettyPrintArrayOfPrimitives;

- (void)testPrettyPrintList;

- (void)testPrettyPrintListOfPrimitiveArrays;

#pragma mark Protected

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalPrettyPrintingTest)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalPrettyPrintingTest_init(ComGoogleGsonFunctionalPrettyPrintingTest *self);

FOUNDATION_EXPORT ComGoogleGsonFunctionalPrettyPrintingTest *new_ComGoogleGsonFunctionalPrettyPrintingTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalPrettyPrintingTest *create_ComGoogleGsonFunctionalPrettyPrintingTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalPrettyPrintingTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonFunctionalPrettyPrintingTest")
