//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "ComGoogleGsonFunctionalTreeTypeAdaptersTest.h"
#include "ComGoogleGsonGson.h"
#include "ComGoogleGsonGsonBuilder.h"
#include "ComGoogleGsonJsonDeserializationContext.h"
#include "ComGoogleGsonJsonDeserializer.h"
#include "ComGoogleGsonJsonElement.h"
#include "ComGoogleGsonJsonParseException.h"
#include "ComGoogleGsonJsonPrimitive.h"
#include "ComGoogleGsonJsonSerializationContext.h"
#include "ComGoogleGsonJsonSerializer.h"
#include "ComGoogleGsonReflectTypeToken.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/reflect/ParameterizedType.h"
#include "java/lang/reflect/Type.h"
#include "java/util/ArrayList.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "junit/framework/TestCase.h"

@class ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment;
@class ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course;
@class ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;
@class ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student;

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest () {
 @public
  ComGoogleGsonGson *gson_;
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *course_;
}

+ (id<JavaUtilList>)createListWithNSObjectArray:(IOSObjectArray *)items;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest, gson_, ComGoogleGsonGson *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest, course_, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *)

inline ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *ComGoogleGsonFunctionalTreeTypeAdaptersTest_get_STUDENT1_ID();
static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, STUDENT1_ID, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)

inline ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *ComGoogleGsonFunctionalTreeTypeAdaptersTest_get_STUDENT2_ID();
static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, STUDENT2_ID, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)

inline ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *ComGoogleGsonFunctionalTreeTypeAdaptersTest_get_STUDENT1();
static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, STUDENT1, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *)

inline ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *ComGoogleGsonFunctionalTreeTypeAdaptersTest_get_STUDENT2();
static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, STUDENT2, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *)

inline id<JavaLangReflectType> ComGoogleGsonFunctionalTreeTypeAdaptersTest_get_TYPE_COURSE_HISTORY();
static id<JavaLangReflectType> ComGoogleGsonFunctionalTreeTypeAdaptersTest_TYPE_COURSE_HISTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, TYPE_COURSE_HISTORY, id<JavaLangReflectType>)

inline ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *ComGoogleGsonFunctionalTreeTypeAdaptersTest_get_COURSE_ID();
static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *ComGoogleGsonFunctionalTreeTypeAdaptersTest_COURSE_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, COURSE_ID, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)

__attribute__((unused)) static id<JavaUtilList> ComGoogleGsonFunctionalTreeTypeAdaptersTest_createListWithNSObjectArray_(IOSObjectArray *items);

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_1)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init();

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id : NSObject {
 @public
  NSString *value_;
  id<JavaLangReflectType> typeOfId_;
}

- (instancetype)initWithNSString:(NSString *)value
         withJavaLangReflectType:(id<JavaLangReflectType>)typeOfId;

- (NSString *)getValue;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id, value_, NSString *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id, typeOfId_, id<JavaLangReflectType>)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *self, NSString *value, id<JavaLangReflectType> typeOfId);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(NSString *value, id<JavaLangReflectType> typeOfId) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(NSString *value, id<JavaLangReflectType> typeOfId);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id)

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                                    withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                                withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter *self);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter)

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student : NSObject {
 @public
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id__;
  NSString *name_;
}

- (instancetype)init;

- (instancetype)initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)id_
                                                          withNSString:(NSString *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student, id__, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student, name_, NSString *)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *self);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init();

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *self, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, NSString *name);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, NSString *name) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, NSString *name);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student)

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course : NSObject {
 @public
  id<JavaUtilList> students_;
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId_;
  jint numAssignments_;
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment_;
}

- (instancetype)init;

- (instancetype)initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)courseId
                                                               withInt:(jint)numAssignments
            withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *)assignment
                                                      withJavaUtilList:(id<JavaUtilList>)players;

- (ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)getId;

- (id<JavaUtilList>)getStudents;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, students_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, courseId_, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, assignment_, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *self);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init();

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *self, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId, jint numAssignments, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment, id<JavaUtilList> players);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId, jint numAssignments, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment, id<JavaUtilList> players) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId, jint numAssignments, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment, id<JavaUtilList> players);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course)

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment : NSObject {
 @public
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id__;
  id data_;
}

- (instancetype)init;

- (instancetype)initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)id_
                                                                withId:(id)data;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment, id__, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)
J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment, data_, id)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *self);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init();

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *self, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, id data);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, id data) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, id data);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment)

@interface ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse : NSObject {
 @public
  jint numClasses_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse)

__attribute__((unused)) static void ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse *self);

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonFunctionalTreeTypeAdaptersTest)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)setUp {
  JreStrongAssign(&gson_, [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_class_() withId:create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init()])) create]);
  JreStrongAssignAndConsume(&course_, new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_COURSE_ID, 4, create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(nil, nil), ComGoogleGsonFunctionalTreeTypeAdaptersTest_createListWithNSObjectArray_([IOSObjectArray arrayWithObjects:(id[]){ ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1, ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2 } count:2 type:ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_class_()])));
}

- (void)testSerializeId {
  NSString *json = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:course_ withJavaLangReflectType:ComGoogleGsonFunctionalTreeTypeAdaptersTest_TYPE_COURSE_HISTORY];
  JunitFrameworkTestCase_assertTrueWithBoolean_([((NSString *) nil_chk(json)) java_contains:NSString_java_valueOf_([((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk(ComGoogleGsonFunctionalTreeTypeAdaptersTest_COURSE_ID)) getValue])]);
  JunitFrameworkTestCase_assertTrueWithBoolean_([json java_contains:NSString_java_valueOf_([((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk(ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1_ID)) getValue])]);
  JunitFrameworkTestCase_assertTrueWithBoolean_([json java_contains:NSString_java_valueOf_([((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk(ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2_ID)) getValue])]);
}

- (void)testDeserializeId {
  NSString *json = @"{courseId:1,students:[{id:1,name:'first'},{id:6,name:'second'}],numAssignments:4,assignment:{}}";
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *target = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withJavaLangReflectType:ComGoogleGsonFunctionalTreeTypeAdaptersTest_TYPE_COURSE_HISTORY];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"1", [((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk(((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *) nil_chk([((id<JavaUtilList>) nil_chk([((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *) nil_chk(target)) getStudents])) getWithInt:0]))->id__)) getValue]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"6", [((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk(((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *) nil_chk([((id<JavaUtilList>) nil_chk([target getStudents])) getWithInt:1]))->id__)) getValue]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"1", [((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk([target getId])) getValue]);
}

+ (id<JavaUtilList>)createListWithNSObjectArray:(IOSObjectArray *)items {
  return ComGoogleGsonFunctionalTreeTypeAdaptersTest_createListWithNSObjectArray_(items);
}

- (void)dealloc {
  RELEASE_(gson_);
  RELEASE_(course_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x8a, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(setUp);
  methods[2].selector = @selector(testSerializeId);
  methods[3].selector = @selector(testDeserializeId);
  methods[4].selector = @selector(createListWithNSObjectArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "STUDENT1_ID", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", .constantValue.asLong = 0, 0x1a, -1, 3, 4, -1 },
    { "STUDENT2_ID", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", .constantValue.asLong = 0, 0x1a, -1, 5, 4, -1 },
    { "STUDENT1", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Student;", .constantValue.asLong = 0, 0x1a, -1, 6, -1, -1 },
    { "STUDENT2", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Student;", .constantValue.asLong = 0, 0x1a, -1, 7, -1, -1 },
    { "TYPE_COURSE_HISTORY", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x1a, -1, 8, -1, -1 },
    { "COURSE_ID", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", .constantValue.asLong = 0, 0x1a, -1, 9, 10, -1 },
    { "gson_", "LComGoogleGsonGson;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "course_", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Course;", .constantValue.asLong = 0, 0x2, -1, -1, 11, -1 },
  };
  static const void *ptrTable[] = { "createList", "[LNSObject;", "<T:Ljava/lang/Object;>([TT;)Ljava/util/List<TT;>;", &ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1_ID, "Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Student;>;", &ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2_ID, &ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1, &ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2, &ComGoogleGsonFunctionalTreeTypeAdaptersTest_TYPE_COURSE_HISTORY, &ComGoogleGsonFunctionalTreeTypeAdaptersTest_COURSE_ID, "Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Course<Lcom/google/gson/functional/TreeTypeAdaptersTest$HistoryCourse;>;>;", "Lcom/google/gson/functional/TreeTypeAdaptersTest$Course<Lcom/google/gson/functional/TreeTypeAdaptersTest$HistoryCourse;>;", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;LComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter;LComGoogleGsonFunctionalTreeTypeAdaptersTest_Student;LComGoogleGsonFunctionalTreeTypeAdaptersTest_Course;LComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment;LComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest = { "TreeTypeAdaptersTest", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x1, 5, 8, -1, 12, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest;
}

+ (void)initialize {
  if (self == [ComGoogleGsonFunctionalTreeTypeAdaptersTest class]) {
    JreStrongAssignAndConsume(&ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1_ID, new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(@"5", ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_class_()));
    JreStrongAssignAndConsume(&ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2_ID, new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(@"6", ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_class_()));
    JreStrongAssignAndConsume(&ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1, new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT1_ID, @"first"));
    JreStrongAssignAndConsume(&ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2, new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_STUDENT2_ID, @"second"));
    JreStrongAssign(&ComGoogleGsonFunctionalTreeTypeAdaptersTest_TYPE_COURSE_HISTORY, [create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init() getType]);
    JreStrongAssignAndConsume(&ComGoogleGsonFunctionalTreeTypeAdaptersTest_COURSE_ID, new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(@"10", ComGoogleGsonFunctionalTreeTypeAdaptersTest_TYPE_COURSE_HISTORY));
    J2OBJC_SET_INITIALIZED(ComGoogleGsonFunctionalTreeTypeAdaptersTest)
  }
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest *self) {
  JunitFrameworkTestCase_init(self);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest, init)
}

id<JavaUtilList> ComGoogleGsonFunctionalTreeTypeAdaptersTest_createListWithNSObjectArray_(IOSObjectArray *items) {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_initialize();
  return JavaUtilArrays_asListWithNSObjectArray_(items);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalTreeTypeAdaptersTest;", "Lcom/google/gson/reflect/TypeToken<Lcom/google/gson/functional/TreeTypeAdaptersTest$Course<Lcom/google/gson/functional/TreeTypeAdaptersTest$HistoryCourse;>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_1;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_1, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_1 *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_1_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_1, init)
}

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id

- (instancetype)initWithNSString:(NSString *)value
         withJavaLangReflectType:(id<JavaLangReflectType>)typeOfId {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(self, value, typeOfId);
  return self;
}

- (NSString *)getValue {
  return value_;
}

- (void)dealloc {
  RELEASE_(value_);
  RELEASE_(typeOfId_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withJavaLangReflectType:);
  methods[1].selector = @selector(getValue);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "LNSString;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "typeOfId_", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LJavaLangReflectType;", "LComGoogleGsonFunctionalTreeTypeAdaptersTest;", "<R:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id = { "Id", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x1a, 2, 2, 1, -1, -1, 2, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *self, NSString *value, id<JavaLangReflectType> typeOfId) {
  NSObject_init(self);
  JreStrongAssign(&self->value_, value);
  JreStrongAssign(&self->typeOfId_, typeOfId);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(NSString *value, id<JavaLangReflectType> typeOfId) {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id, initWithNSString_withJavaLangReflectType_, value, typeOfId)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_(NSString *value, id<JavaLangReflectType> typeOfId) {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id, initWithNSString_withJavaLangReflectType_, value, typeOfId)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                                    withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                                withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  if (!([JavaLangReflectParameterizedType_class_() isInstance:typeOfT])) {
    @throw create_ComGoogleGsonJsonParseException_initWithNSString_(JreStrcat("$@", @"Id of unknown type: ", typeOfT));
  }
  id<JavaLangReflectParameterizedType> parameterizedType = (id<JavaLangReflectParameterizedType>) cast_check(typeOfT, JavaLangReflectParameterizedType_class_());
  id<JavaLangReflectType> typeOfId = IOSObjectArray_Get(nil_chk([((id<JavaLangReflectParameterizedType>) nil_chk(parameterizedType)) getActualTypeArguments]), 0);
  return create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_initWithNSString_withJavaLangReflectType_([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString], typeOfId);
}

- (ComGoogleGsonJsonElement *)serializeWithId:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  return create_ComGoogleGsonJsonPrimitive_initWithNSString_([((ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *) nil_chk(src)) getValue]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", 0x1, 0, 1, 2, 3, -1, -1 },
    { NULL, "LComGoogleGsonJsonElement;", 0x1, 4, 5, -1, 6, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  methods[2].selector = @selector(serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "(Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;Lcom/google/gson/JsonDeserializationContext;)Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<*>;", "serialize", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;LJavaLangReflectType;LComGoogleGsonJsonSerializationContext;", "(Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<*>;Ljava/lang/reflect/Type;Lcom/google/gson/JsonSerializationContext;)Lcom/google/gson/JsonElement;", "LComGoogleGsonFunctionalTreeTypeAdaptersTest;", "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<*>;>;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<*>;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter = { "IdTreeTypeAdapter", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x1a, 3, 0, 7, -1, -1, 8, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest_IdTreeTypeAdapter)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)id_
                                                          withNSString:(NSString *)name {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(self, id_, name);
  return self;
}

- (void)dealloc {
  RELEASE_(id__);
  RELEASE_(name_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "id__", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", .constantValue.asLong = 0, 0x0, 2, -1, 3, -1 },
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;LNSString;", "(Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Student;>;Ljava/lang/String;)V", "id", "Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Student;>;", "LComGoogleGsonFunctionalTreeTypeAdaptersTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student = { "Student", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 2, 2, 4, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *self) {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(self, nil, nil);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student, init)
}

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *self, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, NSString *name) {
  NSObject_init(self);
  JreStrongAssign(&self->id__, id_);
  JreStrongAssign(&self->name_, name);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, NSString *name) {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student, initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_, id_, name)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, NSString *name) {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student, initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withNSString_, id_, name)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Student)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)courseId
                                                               withInt:(jint)numAssignments
            withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *)assignment
                                                      withJavaUtilList:(id<JavaUtilList>)players {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(self, courseId, numAssignments, assignment, players);
  return self;
}

- (ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)getId {
  return courseId_;
}

- (id<JavaUtilList>)getStudents {
  return students_;
}

- (void)dealloc {
  RELEASE_(students_);
  RELEASE_(courseId_);
  RELEASE_(assignment_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", 0x1, -1, -1, -1, 2, -1, -1 },
    { NULL, "LJavaUtilList;", 0x0, -1, -1, -1, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:withInt:withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment:withJavaUtilList:);
  methods[2].selector = @selector(getId);
  methods[3].selector = @selector(getStudents);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "students_", "LJavaUtilList;", .constantValue.asLong = 0, 0x10, -1, -1, 4, -1 },
    { "courseId_", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", .constantValue.asLong = 0, 0x12, -1, -1, 5, -1 },
    { "numAssignments_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "assignment_", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment;", .constantValue.asLong = 0, 0x12, -1, -1, 6, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;ILComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment;LJavaUtilList;", "(Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Course<TT;>;>;ILcom/google/gson/functional/TreeTypeAdaptersTest$Assignment<TT;>;Ljava/util/List<Lcom/google/gson/functional/TreeTypeAdaptersTest$Student;>;)V", "()Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Course<TT;>;>;", "()Ljava/util/List<Lcom/google/gson/functional/TreeTypeAdaptersTest$Student;>;", "Ljava/util/List<Lcom/google/gson/functional/TreeTypeAdaptersTest$Student;>;", "Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Course<TT;>;>;", "Lcom/google/gson/functional/TreeTypeAdaptersTest$Assignment<TT;>;", "LComGoogleGsonFunctionalTreeTypeAdaptersTest;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course = { "Course", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 4, 4, 7, -1, -1, 8, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *self) {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(self, nil, 0, nil, create_JavaUtilArrayList_init());
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, init)
}

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *self, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId, jint numAssignments, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment, id<JavaUtilList> players) {
  NSObject_init(self);
  JreStrongAssign(&self->courseId_, courseId);
  self->numAssignments_ = numAssignments;
  JreStrongAssign(&self->assignment_, assignment);
  JreStrongAssign(&self->students_, players);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId, jint numAssignments, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment, id<JavaUtilList> players) {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_, courseId, numAssignments, assignment, players)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *courseId, jint numAssignments, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *assignment, id<JavaUtilList> players) {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course, initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withInt_withComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_withJavaUtilList_, courseId, numAssignments, assignment, players)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Course)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *)id_
                                                                withId:(id)data {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(self, id_, data);
  return self;
}

- (void)dealloc {
  RELEASE_(id__);
  RELEASE_(data_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id:withId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "id__", "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;", .constantValue.asLong = 0, 0x12, 2, -1, 3, -1 },
    { "data_", "LNSObject;", .constantValue.asLong = 0, 0x12, -1, -1, 4, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalTreeTypeAdaptersTest_Id;LNSObject;", "(Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Assignment<TT;>;>;TT;)V", "id", "Lcom/google/gson/functional/TreeTypeAdaptersTest$Id<Lcom/google/gson/functional/TreeTypeAdaptersTest$Assignment<TT;>;>;", "TT;", "LComGoogleGsonFunctionalTreeTypeAdaptersTest;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment = { "Assignment", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 2, 2, 5, -1, -1, 6, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *self) {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(self, nil, nil);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment, init)
}

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *self, ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, id data) {
  NSObject_init(self);
  JreStrongAssign(&self->id__, id_);
  JreStrongAssign(&self->data_, data);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, id data) {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment, initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_, id_, data)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment_initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Id *id_, id data) {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment, initWithComGoogleGsonFunctionalTreeTypeAdaptersTest_Id_withId_, id_, data)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest_Assignment)

@implementation ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "numClasses_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalTreeTypeAdaptersTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse = { "HistoryCourse", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 1, 1, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse;
}

@end

void ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse *new_ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse, init)
}

ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse *create_ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalTreeTypeAdaptersTest_HistoryCourse)
