//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonFunctionalInheritanceTest")
#ifdef RESTRICT_ComGoogleGsonFunctionalInheritanceTest
#define INCLUDE_ALL_ComGoogleGsonFunctionalInheritanceTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonFunctionalInheritanceTest 1
#endif
#undef RESTRICT_ComGoogleGsonFunctionalInheritanceTest

#if !defined (ComGoogleGsonFunctionalInheritanceTest_) && (INCLUDE_ALL_ComGoogleGsonFunctionalInheritanceTest || defined(INCLUDE_ComGoogleGsonFunctionalInheritanceTest))
#define ComGoogleGsonFunctionalInheritanceTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFunctionalInheritanceTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testBaseSerializedAsBaseWhenSpecifiedWithExplicitType;

- (void)testBaseSerializedAsBaseWhenSpecifiedWithExplicitTypeForToJsonMethod;

- (void)testBaseSerializedAsSub;

- (void)testBaseSerializedAsSubForToJsonMethod;

- (void)testBaseSerializedAsSubWhenSpecifiedWithExplicitType;

- (void)testBaseSerializedAsSubWhenSpecifiedWithExplicitTypeForToJsonMethod;

- (void)testBasicFinals;

- (void)testClassWithBaseArrayFieldSerialization;

- (void)testClassWithBaseCollectionFieldSerialization;

- (void)testClassWithBaseFieldSerialization;

- (void)testFinalReflection;

- (void)testSubClassDeserialization;

- (void)testSubClassSerialization;

- (void)testSubInterfacesOfCollectionDeserialization;

- (void)testSubInterfacesOfCollectionSerialization;

#pragma mark Protected

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalInheritanceTest)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalInheritanceTest_init(ComGoogleGsonFunctionalInheritanceTest *self);

FOUNDATION_EXPORT ComGoogleGsonFunctionalInheritanceTest *new_ComGoogleGsonFunctionalInheritanceTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalInheritanceTest *create_ComGoogleGsonFunctionalInheritanceTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalInheritanceTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonFunctionalInheritanceTest")
