//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "ComGoogleGsonCommonTestTypes.h"
#include "ComGoogleGsonFunctionalCustomDeserializerTest.h"
#include "ComGoogleGsonGson.h"
#include "ComGoogleGsonGsonBuilder.h"
#include "ComGoogleGsonJsonDeserializationContext.h"
#include "ComGoogleGsonJsonDeserializer.h"
#include "ComGoogleGsonJsonElement.h"
#include "ComGoogleGsonJsonObject.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/reflect/Type.h"
#include "junit/framework/TestCase.h"

@class ComGoogleGsonFunctionalCustomDeserializerTest_MyBase;

@interface ComGoogleGsonFunctionalCustomDeserializerTest () {
 @public
  ComGoogleGsonGson *gson_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest, gson_, ComGoogleGsonGson *)

inline NSString *ComGoogleGsonFunctionalCustomDeserializerTest_get_DEFAULT_VALUE();
static NSString *ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE = @"test123";
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalCustomDeserializerTest, DEFAULT_VALUE, NSString *)

inline NSString *ComGoogleGsonFunctionalCustomDeserializerTest_get_SUFFIX();
static NSString *ComGoogleGsonFunctionalCustomDeserializerTest_SUFFIX = @"blah";
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalCustomDeserializerTest, SUFFIX, NSString *)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder : NSObject {
 @public
  NSString *data_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)data;

- (NSString *)getData;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder, data_, NSString *)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init();

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *self, NSString *data);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(NSString *data) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(NSString *data);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper : NSObject {
 @public
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *wrappedData_;
}

- (instancetype)init;

- (instancetype)initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder:(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)data;

- (ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)getWrappedData;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper, wrappedData_, ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init();

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *self, ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer : NSObject < ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                                              withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                                          withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_1 : NSObject < ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                                          withJavaLangReflectType:(id<JavaLangReflectType>)pojoType
                                                      withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_1)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_1_init(ComGoogleGsonFunctionalCustomDeserializerTest_1 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_1 *new_ComGoogleGsonFunctionalCustomDeserializerTest_1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_1 *create_ComGoogleGsonFunctionalCustomDeserializerTest_1_init();

@interface ComGoogleGsonFunctionalCustomDeserializerTest_MyBase : NSObject

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase)

inline NSString *ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_get_TYPE_ACCESS();
static NSString *ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_TYPE_ACCESS = @"__type__";
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase, TYPE_ACCESS, NSString *)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *new_ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *create_ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase)

typedef NS_ENUM(NSUInteger, ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_Enum) {
  ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_Enum_SUB_TYPE1 = 0,
  ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_Enum_SUB_TYPE2 = 1,
};

@interface ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes : JavaLangEnum < NSCopying > {
 @public
  id<JavaLangReflectType> subClass_;
}

- (id<JavaLangReflectType>)getSubclass;

+ (IOSObjectArray *)values;

+ (ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values_[];

inline ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_get_SUB_TYPE1();
J2OBJC_ENUM_CONSTANT(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, SUB_TYPE1)

inline ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_get_SUB_TYPE2();
J2OBJC_ENUM_CONSTANT(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, SUB_TYPE2)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, subClass_, id<JavaLangReflectType>)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initWithJavaLangReflectType_withNSString_withInt_(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *self, id<JavaLangReflectType> subClass, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values();

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 : ComGoogleGsonFunctionalCustomDeserializerTest_MyBase {
 @public
  NSString *field1_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1, field1_, NSString *)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *new_ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *create_ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 : ComGoogleGsonFunctionalCustomDeserializerTest_MyBase {
 @public
  NSString *field2_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2, field2_, NSString *)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 *new_ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 *create_ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2)

@interface ComGoogleGsonFunctionalCustomDeserializerTest_2 : NSObject < ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_2)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_2_init(ComGoogleGsonFunctionalCustomDeserializerTest_2 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_2 *new_ComGoogleGsonFunctionalCustomDeserializerTest_2_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_2 *create_ComGoogleGsonFunctionalCustomDeserializerTest_2_init();

@interface ComGoogleGsonFunctionalCustomDeserializerTest_3 : NSObject < ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_3)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_3_init(ComGoogleGsonFunctionalCustomDeserializerTest_3 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_3 *new_ComGoogleGsonFunctionalCustomDeserializerTest_3_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_3 *create_ComGoogleGsonFunctionalCustomDeserializerTest_3_init();

@interface ComGoogleGsonFunctionalCustomDeserializerTest_4 : NSObject < ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_4)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_4_init(ComGoogleGsonFunctionalCustomDeserializerTest_4 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_4 *new_ComGoogleGsonFunctionalCustomDeserializerTest_4_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_4 *create_ComGoogleGsonFunctionalCustomDeserializerTest_4_init();

@interface ComGoogleGsonFunctionalCustomDeserializerTest_5 : NSObject < ComGoogleGsonJsonDeserializer >

- (instancetype)init;

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_5)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_5_init(ComGoogleGsonFunctionalCustomDeserializerTest_5 *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_5 *new_ComGoogleGsonFunctionalCustomDeserializerTest_5_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_5 *create_ComGoogleGsonFunctionalCustomDeserializerTest_5_init();

@interface ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray : NSObject {
 @public
  IOSObjectArray *bases_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray)

J2OBJC_FIELD_SETTER(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray, bases_, IOSObjectArray *)

__attribute__((unused)) static void ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *self);

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *new_ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *create_ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)setUp {
  [super setUp];
  JreStrongAssign(&gson_, [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_class_() withId:create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init()])) create]);
}

- (void)testDefaultConstructorNotCalledOnObject {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data = create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE);
  NSString *json = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:data];
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *actual = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_class_()];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(JreStrcat("$$", ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE, ComGoogleGsonFunctionalCustomDeserializerTest_SUFFIX), [((ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *) nil_chk(actual)) getData]);
}

- (void)testDefaultConstructorNotCalledOnField {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *dataWrapper = create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE));
  NSString *json = [((ComGoogleGsonGson *) nil_chk(gson_)) toJsonWithId:dataWrapper];
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *actual = [((ComGoogleGsonGson *) nil_chk(gson_)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_class_()];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(JreStrcat("$$", ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE, ComGoogleGsonFunctionalCustomDeserializerTest_SUFFIX), [((ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *) nil_chk([((ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *) nil_chk(actual)) getWrappedData])) getData]);
}

- (void)testJsonTypeFieldBasedDeserialization {
  NSString *json = @"{field1:'abc',field2:'def',__type__:'SUB_TYPE1'}";
  ComGoogleGsonGson *gson = [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_class_() withId:create_ComGoogleGsonFunctionalCustomDeserializerTest_1_init()])) create];
  ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *target = (ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *) cast_chk([((ComGoogleGsonGson *) nil_chk(gson)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_class_()], [ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 class]);
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(@"abc", ((ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *) nil_chk(target))->field1_);
}

- (void)testCustomDeserializerReturnsNullForTopLevelObject {
  ComGoogleGsonGson *gson = [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonCommonTestTypes_Base_class_() withId:create_ComGoogleGsonFunctionalCustomDeserializerTest_2_init()])) create];
  NSString *json = @"{baseName:'Base',subName:'SubRevised'}";
  ComGoogleGsonCommonTestTypes_Base *target = [((ComGoogleGsonGson *) nil_chk(gson)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonCommonTestTypes_Base_class_()];
  JunitFrameworkTestCase_assertNullWithId_(target);
}

- (void)testCustomDeserializerReturnsNull {
  ComGoogleGsonGson *gson = [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonCommonTestTypes_Base_class_() withId:create_ComGoogleGsonFunctionalCustomDeserializerTest_3_init()])) create];
  NSString *json = @"{base:{baseName:'Base',subName:'SubRevised'}}";
  ComGoogleGsonCommonTestTypes_ClassWithBaseField *target = [((ComGoogleGsonGson *) nil_chk(gson)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonCommonTestTypes_ClassWithBaseField_class_()];
  JunitFrameworkTestCase_assertNullWithId_(((ComGoogleGsonCommonTestTypes_ClassWithBaseField *) nil_chk(target))->base_);
}

- (void)testCustomDeserializerReturnsNullForArrayElements {
  ComGoogleGsonGson *gson = [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonCommonTestTypes_Base_class_() withId:create_ComGoogleGsonFunctionalCustomDeserializerTest_4_init()])) create];
  NSString *json = @"[{baseName:'Base'},{baseName:'Base'}]";
  IOSObjectArray *target = [((ComGoogleGsonGson *) nil_chk(gson)) fromJsonWithNSString:json withIOSClass:IOSClass_arrayType(ComGoogleGsonCommonTestTypes_Base_class_(), 1)];
  JunitFrameworkTestCase_assertNullWithId_(IOSObjectArray_Get(nil_chk(target), 0));
  JunitFrameworkTestCase_assertNullWithId_(IOSObjectArray_Get(target, 1));
}

- (void)testCustomDeserializerReturnsNullForArrayElementsForArrayField {
  ComGoogleGsonGson *gson = [((ComGoogleGsonGsonBuilder *) nil_chk([create_ComGoogleGsonGsonBuilder_init() registerTypeAdapterWithJavaLangReflectType:ComGoogleGsonCommonTestTypes_Base_class_() withId:create_ComGoogleGsonFunctionalCustomDeserializerTest_5_init()])) create];
  NSString *json = @"{bases:[{baseName:'Base'},{baseName:'Base'}]}";
  ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *target = [((ComGoogleGsonGson *) nil_chk(gson)) fromJsonWithNSString:json withIOSClass:ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_class_()];
  JunitFrameworkTestCase_assertNullWithId_(IOSObjectArray_Get(nil_chk(((ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *) nil_chk(target))->bases_), 0));
  JunitFrameworkTestCase_assertNullWithId_(IOSObjectArray_Get(nil_chk(target->bases_), 1));
}

- (void)dealloc {
  RELEASE_(gson_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(setUp);
  methods[2].selector = @selector(testDefaultConstructorNotCalledOnObject);
  methods[3].selector = @selector(testDefaultConstructorNotCalledOnField);
  methods[4].selector = @selector(testJsonTypeFieldBasedDeserialization);
  methods[5].selector = @selector(testCustomDeserializerReturnsNullForTopLevelObject);
  methods[6].selector = @selector(testCustomDeserializerReturnsNull);
  methods[7].selector = @selector(testCustomDeserializerReturnsNullForArrayElements);
  methods[8].selector = @selector(testCustomDeserializerReturnsNullForArrayElementsForArrayField);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_VALUE", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 1, -1, -1 },
    { "SUFFIX", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 2, -1, -1 },
    { "gson_", "LComGoogleGsonGson;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaLangException;", &ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE, &ComGoogleGsonFunctionalCustomDeserializerTest_SUFFIX, "LComGoogleGsonFunctionalCustomDeserializerTest_DataHolder;LComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper;LComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer;LComGoogleGsonFunctionalCustomDeserializerTest_MyBase;LComGoogleGsonFunctionalCustomDeserializerTest_SubTypes;LComGoogleGsonFunctionalCustomDeserializerTest_SubType1;LComGoogleGsonFunctionalCustomDeserializerTest_SubType2;LComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest = { "CustomDeserializerTest", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x1, 9, 3, -1, 3, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_init(ComGoogleGsonFunctionalCustomDeserializerTest *self) {
  JunitFrameworkTestCase_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest *new_ComGoogleGsonFunctionalCustomDeserializerTest_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest *create_ComGoogleGsonFunctionalCustomDeserializerTest_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)data {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(self, data);
  return self;
}

- (NSString *)getData {
  return data_;
}

- (void)dealloc {
  RELEASE_(data_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(getData);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "data_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LComGoogleGsonFunctionalCustomDeserializerTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder = { "DataHolder", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 3, 1, 1, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *self) {
  NSObject_init(self);
  @throw create_JavaLangIllegalStateException_init();
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder, init)
}

void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *self, NSString *data) {
  NSObject_init(self);
  JreStrongAssign(&self->data_, data);
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(NSString *data) {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder, initWithNSString_, data)
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(NSString *data) {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder, initWithNSString_, data)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder:(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)data {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(self, data);
  return self;
}

- (ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)getWrappedData {
  return wrappedData_;
}

- (void)dealloc {
  RELEASE_(wrappedData_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalCustomDeserializerTest_DataHolder;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder:);
  methods[2].selector = @selector(getWrappedData);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "wrappedData_", "LComGoogleGsonFunctionalCustomDeserializerTest_DataHolder;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalCustomDeserializerTest_DataHolder;", "LComGoogleGsonFunctionalCustomDeserializerTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper = { "DataHolderWrapper", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 3, 1, 1, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *self) {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(self, create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(ComGoogleGsonFunctionalCustomDeserializerTest_DEFAULT_VALUE));
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper, init)
}

void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *self, ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data) {
  NSObject_init(self);
  JreStrongAssign(&self->wrappedData_, data);
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data) {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper, initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_, data)
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper_initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *data) {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper, initWithComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_, data)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderWrapper)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                                              withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                                          withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  ComGoogleGsonJsonObject *jsonObj = [((ComGoogleGsonJsonElement *) nil_chk(json)) getAsJsonObject];
  NSString *dataString = [((ComGoogleGsonJsonElement *) nil_chk([((ComGoogleGsonJsonObject *) nil_chk(jsonObj)) getWithNSString:@"data"])) getAsString];
  return create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolder_initWithNSString_(JreStrcat("$$", dataString, ComGoogleGsonFunctionalCustomDeserializerTest_SUFFIX));
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalCustomDeserializerTest_DataHolder;", 0x1, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalCustomDeserializerTest;", "Ljava/lang/Object;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/functional/CustomDeserializerTest$DataHolder;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer = { "DataHolderDeserializer", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0xa, 2, 0, 3, -1, -1, 4, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer *new_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer *create_ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_DataHolderDeserializer)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                                          withJavaLangReflectType:(id<JavaLangReflectType>)pojoType
                                                      withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  NSString *type = [((ComGoogleGsonJsonElement *) nil_chk([((ComGoogleGsonJsonObject *) nil_chk([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsJsonObject])) getWithNSString:ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_TYPE_ACCESS])) getAsString];
  return [((id<ComGoogleGsonJsonDeserializationContext>) nil_chk(context)) deserializeWithComGoogleGsonJsonElement:json withJavaLangReflectType:[((ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *) nil_chk(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_valueOfWithNSString_(type))) getSubclass]];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalCustomDeserializerTest_MyBase;", 0x1, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalCustomDeserializerTest;", "testJsonTypeFieldBasedDeserialization", "Ljava/lang/Object;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/functional/CustomDeserializerTest$MyBase;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_1 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 3, -1, 4, 5, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_1;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_1_init(ComGoogleGsonFunctionalCustomDeserializerTest_1 *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_1 *new_ComGoogleGsonFunctionalCustomDeserializerTest_1_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_1, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_1 *create_ComGoogleGsonFunctionalCustomDeserializerTest_1_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_1, init)
}

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_MyBase

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TYPE_ACCESS", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 0, -1, -1 },
  };
  static const void *ptrTable[] = { &ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_TYPE_ACCESS, "LComGoogleGsonFunctionalCustomDeserializerTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_MyBase = { "MyBase", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 1, 1, 1, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_MyBase;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *new_ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_MyBase *create_ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_MyBase)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes)

ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values_[2];

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes

- (id<JavaLangReflectType>)getSubclass {
  return subClass_;
}

+ (IOSObjectArray *)values {
  return ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values();
}

+ (ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *)valueOfWithNSString:(NSString *)name {
  return ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LJavaLangReflectType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LComGoogleGsonFunctionalCustomDeserializerTest_SubTypes;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonFunctionalCustomDeserializerTest_SubTypes;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getSubclass);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SUB_TYPE1", "LComGoogleGsonFunctionalCustomDeserializerTest_SubTypes;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "SUB_TYPE2", "LComGoogleGsonFunctionalCustomDeserializerTest_SubTypes;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "subClass_", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, SUB_TYPE1), &JreEnum(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, SUB_TYPE2), "LComGoogleGsonFunctionalCustomDeserializerTest;", "Ljava/lang/Enum<Lcom/google/gson/functional/CustomDeserializerTest$SubTypes;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes = { "SubTypes", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x401a, 3, 3, 4, -1, -1, 5, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes;
}

+ (void)initialize {
  if (self == [ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 2 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, SUB_TYPE1) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initWithJavaLangReflectType_withNSString_withInt_(e, ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_class_(), @"SUB_TYPE1", 0);
    (JreEnum(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes, SUB_TYPE2) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initWithJavaLangReflectType_withNSString_withInt_(e, ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_class_(), @"SUB_TYPE2", 1);
    J2OBJC_SET_INITIALIZED(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes)
  }
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initWithJavaLangReflectType_withNSString_withInt_(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *self, id<JavaLangReflectType> subClass, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  JreStrongAssign(&self->subClass_, subClass);
}

IOSObjectArray *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values() {
  ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initialize();
  return [IOSObjectArray arrayWithObjects:ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values_ count:2 type:ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_class_()];
}

ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_valueOfWithNSString_(NSString *name) {
  ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initialize();
  for (int i = 0; i < 2; i++) {
    ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *e = ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes *ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_fromOrdinal(NSUInteger ordinal) {
  ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_initialize();
  if (ordinal >= 2) {
    return nil;
  }
  return ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_SubTypes)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_SubType1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(field1_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "field1_", "LNSString;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalCustomDeserializerTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 = { "SubType1", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 1, 1, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_SubType1;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *self) {
  ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *new_ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_SubType1 *create_ComGoogleGsonFunctionalCustomDeserializerTest_SubType1_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_SubType1)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_SubType2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(field2_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "field2_", "LNSString;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalCustomDeserializerTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 = { "SubType2", "com.google.gson.functional", ptrTable, methods, fields, 7, 0xa, 1, 1, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_SubType2;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 *self) {
  ComGoogleGsonFunctionalCustomDeserializerTest_MyBase_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 *new_ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_SubType2 *create_ComGoogleGsonFunctionalCustomDeserializerTest_SubType2_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_SubType2)

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonCommonTestTypes_Base;", 0x1, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalCustomDeserializerTest;", "testCustomDeserializerReturnsNullForTopLevelObject", "Ljava/lang/Object;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/common/TestTypes$Base;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_2 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 3, -1, 4, 5, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_2;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_2_init(ComGoogleGsonFunctionalCustomDeserializerTest_2 *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_2 *new_ComGoogleGsonFunctionalCustomDeserializerTest_2_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_2, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_2 *create_ComGoogleGsonFunctionalCustomDeserializerTest_2_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_2, init)
}

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_3

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_3_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonCommonTestTypes_Base;", 0x1, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalCustomDeserializerTest;", "testCustomDeserializerReturnsNull", "Ljava/lang/Object;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/common/TestTypes$Base;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_3 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 3, -1, 4, 5, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_3;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_3_init(ComGoogleGsonFunctionalCustomDeserializerTest_3 *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_3 *new_ComGoogleGsonFunctionalCustomDeserializerTest_3_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_3, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_3 *create_ComGoogleGsonFunctionalCustomDeserializerTest_3_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_3, init)
}

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_4

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_4_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonCommonTestTypes_Base;", 0x1, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalCustomDeserializerTest;", "testCustomDeserializerReturnsNullForArrayElements", "Ljava/lang/Object;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/common/TestTypes$Base;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_4 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 3, -1, 4, 5, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_4;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_4_init(ComGoogleGsonFunctionalCustomDeserializerTest_4 *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_4 *new_ComGoogleGsonFunctionalCustomDeserializerTest_4_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_4, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_4 *create_ComGoogleGsonFunctionalCustomDeserializerTest_4_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_4, init)
}

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_5

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_5_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleGsonCommonTestTypes_Base *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonCommonTestTypes_Base;", 0x1, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "LComGoogleGsonFunctionalCustomDeserializerTest;", "testCustomDeserializerReturnsNullForArrayElementsForArrayField", "Ljava/lang/Object;Lcom/google/gson/JsonDeserializer<Lcom/google/gson/common/TestTypes$Base;>;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_5 = { "", "com.google.gson.functional", ptrTable, methods, NULL, 7, 0x8018, 2, 0, 3, -1, 4, 5, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_5;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_5_init(ComGoogleGsonFunctionalCustomDeserializerTest_5 *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_5 *new_ComGoogleGsonFunctionalCustomDeserializerTest_5_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_5, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_5 *create_ComGoogleGsonFunctionalCustomDeserializerTest_5_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_5, init)
}

@implementation ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(bases_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "bases_", "[LComGoogleGsonCommonTestTypes_Base;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleGsonFunctionalCustomDeserializerTest;" };
  static const J2ObjcClassInfo _ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray = { "ClassWithBaseArray", "com.google.gson.functional", ptrTable, methods, fields, 7, 0x1a, 1, 1, 0, -1, -1, -1, -1 };
  return &_ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray;
}

@end

void ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *self) {
  NSObject_init(self);
}

ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *new_ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init() {
  J2OBJC_NEW_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray, init)
}

ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray *create_ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray_init() {
  J2OBJC_CREATE_IMPL(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonFunctionalCustomDeserializerTest_ClassWithBaseArray)
