//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonRegressionJsonAdapterNullSafeTest")
#ifdef RESTRICT_ComGoogleGsonRegressionJsonAdapterNullSafeTest
#define INCLUDE_ALL_ComGoogleGsonRegressionJsonAdapterNullSafeTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonRegressionJsonAdapterNullSafeTest 1
#endif
#undef RESTRICT_ComGoogleGsonRegressionJsonAdapterNullSafeTest

#if !defined (ComGoogleGsonRegressionJsonAdapterNullSafeTest_) && (INCLUDE_ALL_ComGoogleGsonRegressionJsonAdapterNullSafeTest || defined(INCLUDE_ComGoogleGsonRegressionJsonAdapterNullSafeTest))
#define ComGoogleGsonRegressionJsonAdapterNullSafeTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonRegressionJsonAdapterNullSafeTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testNullSafeBugDeserialize;

- (void)testNullSafeBugSerialize;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonRegressionJsonAdapterNullSafeTest)

FOUNDATION_EXPORT void ComGoogleGsonRegressionJsonAdapterNullSafeTest_init(ComGoogleGsonRegressionJsonAdapterNullSafeTest *self);

FOUNDATION_EXPORT ComGoogleGsonRegressionJsonAdapterNullSafeTest *new_ComGoogleGsonRegressionJsonAdapterNullSafeTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonRegressionJsonAdapterNullSafeTest *create_ComGoogleGsonRegressionJsonAdapterNullSafeTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonRegressionJsonAdapterNullSafeTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonRegressionJsonAdapterNullSafeTest")
