//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonFunctionalInterfaceTest")
#ifdef RESTRICT_ComGoogleGsonFunctionalInterfaceTest
#define INCLUDE_ALL_ComGoogleGsonFunctionalInterfaceTest 0
#else
#define INCLUDE_ALL_ComGoogleGsonFunctionalInterfaceTest 1
#endif
#undef RESTRICT_ComGoogleGsonFunctionalInterfaceTest

#if !defined (ComGoogleGsonFunctionalInterfaceTest_) && (INCLUDE_ALL_ComGoogleGsonFunctionalInterfaceTest || defined(INCLUDE_ComGoogleGsonFunctionalInterfaceTest))
#define ComGoogleGsonFunctionalInterfaceTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@interface ComGoogleGsonFunctionalInterfaceTest : JunitFrameworkTestCase

#pragma mark Public

- (instancetype)init;

- (void)testSerializingInterfaceObjectField;

- (void)testSerializingObjectImplementingInterface;

#pragma mark Protected

- (void)setUp;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFunctionalInterfaceTest)

FOUNDATION_EXPORT void ComGoogleGsonFunctionalInterfaceTest_init(ComGoogleGsonFunctionalInterfaceTest *self);

FOUNDATION_EXPORT ComGoogleGsonFunctionalInterfaceTest *new_ComGoogleGsonFunctionalInterfaceTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonFunctionalInterfaceTest *create_ComGoogleGsonFunctionalInterfaceTest_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFunctionalInterfaceTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonFunctionalInterfaceTest")
